// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpmkojhglqrifzqoehya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wbWtvamhnbHFyaWZ6cW9laHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mzk2MjIsImV4cCI6MjA2OTIxNTYyMn0.QiFxkMggL2UbG_NsUAsoa76JRzyaypACJrzWZpfQP9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});